---
title: "Gravitational Wave Analysis in Python"
subtitle: "CSE 515: Software Design For Data Science"
author: "Hannah Luebbering"
output:
  html_document: 
    css: assets/main.css
    toc: yes
    toc_float: yes
bibliography: static/references.bib
nocite: '@*'
# knit: pagedown::chrome_print
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = ".") })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

```



WRITTEN REPORT OF FINAL PROJECT

## Introduction



```{r, fig.cap="Simulated Data Example"}
simulated.df <- read.csv("assets/data/out.csv")
kable(head(simulated.df, 8), col.names = c("Strain Amplitude", "Frequency"), escape = FALSE) %>%
  kable_styling(full_width = FALSE, font_size = 10, html_font = "Roboto Condensed", bootstrap_options = c("striped", "hover"))
```




```{r}
table1 <- read.csv("assets/data/table1.csv")
table2 <- read.csv("assets/data/table2.csv")

colnames(table1) <- c("Source", "$I_\\mathrm{Gal}$", "$b_\\mathrm{Gal}$",
                      "Orbital Period", "$m_1$", "$m_2$", 
                      "t", "Refs", "Type")

colnames(table2) <- c("Source", "f (mHz)", "$\\beta$ (mas)",
                      "$\\sigma_\\beta$ (mas)", "d (pc)", 
                      "$\\sigma_d$ (pc)", "$\\mathcal{A}$",
                      "SNR", "type")

kable(table1, escape = FALSE) %>% kable_styling(font_size = 9) %>%
  group_rows(start_row = 1, end_row = 11, group_label = "AM CVn type") %>%
  group_rows(start_row = 12, end_row = 15, group_label = "Detached white dwarfs") %>%
  group_rows(start_row = 16, end_row = 16, group_label = "Hot subdwarf binaries") %>% remove_column(columns = 9)
  
kable(table2, escape = FALSE) %>% kable_styling(font_size = 9) %>%
  group_rows(start_row = 1, end_row = 11, group_label = "AM CVn type") %>%
  group_rows(start_row = 12, end_row = 15, group_label = "Detached white dwarfs") %>%
  group_rows(start_row = 16, end_row = 16, group_label = "Hot subdwarf binaries") %>% remove_column(columns = 9)
```



```{r, fig.cap="Parameters of the analytic fit the Galactic confusion noise as described by equation (14). The amplitude A has been fixed to $9 \\times 10^{−45}$."}
gcn <- data.frame("6 mo" = c(0.133, 243, 482, 917, 0.00258),
                  "1 yr" = c(0.171, 292, 1020, 1680, 0.00215),
                  "2 yr" = c(0.165, 299, 611, 1340, 0.00173),
                  "4 yr" = c(0.138, -221, 521, 1680, 0.00113),
                  row.names = c("$\\alpha$", "$\\beta$", "$\\kappa$",
                                "$\\gamma$", "$f_\\kappa$"))

kable(gcn, escape = FALSE, col.names = c("6 mo", "1 yr", "2 yr", "4 yr"))
```



--------------------------------------------

## Description of user / use cases

(a.k.a., functional spec)









--------------------------------------------


## Description of software modules / components

(a.k.a., component spec)	

The above should definitely include modules and classes, but detailed function explanation optional depending on size of project




--------------------------------------------

## Discussion


 of at least two design decisions made and why you made them

--------------------------------------------

## Comparison 

Comparison to the design of some existing software library	


--------------------------------------------

## Discussion of extensibility


Discussion of extensibility of your software (i.e., how difficult is it to extend?)	


--------------------------------------------



## References 
